apiVersion: apps/v1
kind: Deployment
metadata:
  name: aminu-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
      annotations:
        # These 3 lines are the "Zero-Trust" magic
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "webapp"
        vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/webapp/config"
    spec:
      serviceAccountName: default
      containers:
      - name: web
        image: nginx:latest
        ports:
        - containerPort: 80
